name: talker_http_logger
description: Lightweight and customizable http client logger on talker base
version: 5.0.0-dev.7
homepage: https://github.com/Frezyx/talker

environment:
  sdk: ^3.0.3

dependencies:
  http_interceptor: ^2.0.0
  talker: ^5.0.0-dev.7

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
